# Generated by Django 4.2.4 on 2023-08-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0003_alter_userpayments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField(max_length=300)),
                ('payment_interval', models.TextField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
